### ISSUE TITLE
Add error message when Apple actions fail for lack of secrets

### ISSUE THREAD

**Issue by Muirrum** [hackclub/burrow#105]
Currently, the Apple builds are failing because of an insecure option being passed to a command (see example [here](https://github.com/hackclub/burrow/actions/runs/5193926796/jobs/9365051369))

This is causing tests to fail before they can even begin.

**Comment by Muirrum** [comment]
https://github.com/hackclub/burrow/blob/main/.github/actions/import-cert/action.yml#LL24C34-L24C34

Looks like it's failing to inject the secret for the certificate. See #86

**Comment by conradev** [comment]
https://github.com/hackclub/burrow/pull/86#issuecomment-1586190480

Let's use this issue to track implementing a better error message for missing secrets so that people know how to resolve the issue
