### ISSUE TITLE
Create OpenOptions-like structure to create TunInterface

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#113]
We should create a structure like [`OpenOptions`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html) to open our `TunInterface`.

We should have it reflect the underlying operating system as much as possible and only expose options that are available on a given platform. Some common ones:

- Windows and Linux support naming the interface, whereas macOS does not
- Linux has Linux-only flags like `IFF_TUN_EXCL` and `IFF_NO_PI`

We can then make OS-specific functions to create the interface inside of the `burrow` crate

**Comment by davnotdev** [comment]
Would be glad to work on this.
