### ISSUE TITLE
Crash report collection on linux

### ISSUE THREAD

**Issue by karamassie** [hackclub/burrow#124]

**Comment by Muirrum** [comment]
What do you mean by collection? Dumping crash logs to the local machine? Sending them out to an external server?

**Comment by Sarvesh-Mk** [comment]
I can work on this issue!

**Comment by karamassie** [comment]
can we find a crash reporter instead of building it - conrad

**Comment by jdogcoder** [comment]
How do we feel about sentry?

**Comment by jdogcoder** [comment]
@conradev are you cool if I rename this to include crash logs for multiplatform? Or are we specifically looking for Linux?

**Comment by jdogcoder** [comment]
Unassigninf for now, as this is for further down the line per discussion with conrad.
