### ISSUE TITLE
Error handling in `burrow` crate

### ISSUE THREAD

**Issue by davnotdev** [hackclub/burrow#139]
Right now, in the `burrow` crate, all results are of type `tokio::io::Result` which is just `std::io::Result`. However, this isn't representative of every type of error. Instead, we should either bring in `thiserror` and `anyhow`, or implement our own error type.

**Comment by conradev** [comment]
Yes! Let's use `anyhow` for now, and feel free to start using it to unblock you

**Comment by davnotdev** [comment]
This is done in #153, closing.
