### ISSUE TITLE
Missing Contributing.md

### ISSUE THREAD

**Issue by maxwofford** [hackclub/burrow#146]
There's a line in the README.md that tries to link to a CONTRIBUTING.md file that doesn't exist. Seems like we want to add one to the repo or remove that line.

**Comment by ma1ted** [comment]
@conradev I've edited @Muirrum's draft; it should be good to merge #102.

**Comment by ma1ted** [comment]
That way we can close this too.

**Comment by karamassie** [comment]
closed as dupe #20
