### ISSUE TITLE
Decide on a Rust crate to use for the WireGuard implementation

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#18]

**Comment by Muirrum** [comment]
https://crates.io/crates/wireguard-control

This is the crate that I use for `bridged`, it has high-level bindings but uses `wireguard-control-sys` underneath

**Comment by conradev** [comment]
That crate is neat because it abstracts across kernel and userspace Wireguard libraries, but it depends on Wireguard being installed elsewhere and doesn't contain an implementation itself.

We'll ultimately need Wireguard to be statically compiled in for it to work on all platforms, and in order to do things like run it over WebRTC

**Comment by conradev** [comment]
Updates:

This looks like it could work, if it exposes functionality as a library: https://github.com/WireGuard/wireguard-rs
This looks like we could take inspiration from this: https://github.com/cloudflare/boringtun
