### ISSUE TITLE
Add GPL-3 license to the repository

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#21]

**Comment by Soumya-Kushwaha** [comment]
I'd do..

**Comment by reesericci** [comment]
I think it would be wise to consider using the AGPL because it has stronger protections for distributing over the network

**Comment by conradev** [comment]
I don't want to use the AGPL because burrow is networking software.

I want people to be able to use a custom version of burrow as a part of the network infrastructure of a commercial product without having to make their source public, if that makes sense, like one might use nginx. It's nuanced: https://news.ycombinator.com/item?id=24195641

**Comment by reesericci** [comment]
> I want people to be able to use a custom version of burrow as a part of the network infrastructure of a commercial product without having to make their source public, if that makes sense.

I think our views differ here; this is exactly why I want to use the AGPL - I believe people should have to provide source when its used in a commercial product.

**Comment by zachlatta** [comment]
Conrad and I discussed AGPL vs GPL-3, and believe that if we want people to
actually be able to use Burrow, it needs to be GPL-3. I think that is
already much more copyleft than the Hack Club default of MIT, so I think we
should stick w this.

**Comment by reesericci** [comment]
Not to be rude, but what do you define as "actually be able to use Burrow"?

**Comment by zachlatta** [comment]
Many companies aren’t allowed to use AGPL code because it doesn’t have much
precedence in the courts, and because since this is a networking tool it
has unclear implications for the rest of the network.

**Comment by reesericci** [comment]
Oh that's interesting - ok.
