### ISSUE TITLE
.local TLD registration

### ISSUE THREAD

**Issue by reesericci** [hackclub/burrow#27]
It would be cool if burrowers could register domains on the .local TLD, to host websites, file servers, etc locally on a burrownet.

**Comment by alx-alexpark** [comment]
Also arbitrary TLDs

**Comment by youngchief-btw** [comment]
Would it be better if we did .burrow as the TLD?

**Comment by reesericci** [comment]
The reason I suggest using .local is that it's guaranteed by ICANN to never conflict with other TLDs, although it might conflict with mDNS, something worth looking into

https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xml

**Comment by karamassie** [comment]
we do plan on doing this, but there isnt any current discussion to be had on it. closing for now :)
