### ISSUE TITLE
Protocol for app <-> VPN communication

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#30]

**Comment by reesericci** [comment]
![image](https://user-images.githubusercontent.com/19589006/232941859-8a1c14e7-ae89-4650-b1a5-86a30cd2890f.png)

**Comment by conradev** [comment]
Transports to explore:
- HTTP
- WebSockets
- D-Bus
- XPC

**Comment by conradev** [comment]
I'm going to close this issue because we have a separate issue for systemd (and general client/daemon communication) on Linux. Communication on macOS is largely solved.
