### ISSUE TITLE
Implement Linux daemon for burrow

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#34]

**Comment by Muirrum** [comment]
What do you mean by "systemd server"?

**Comment by conradev** [comment]
@Muirrum a socket-activatable user service in systemd

**Comment by Muirrum** [comment]
We shouldn't be depending on systemd.

**Comment by Muirrum** [comment]
this isn't about a service file. this is about using `libsystemd`

**Comment by conradev** [comment]
As a baseline, Rust has a whole system for optional dependencies, and we can decide to only link `libsystemd` if the optional feature is enabled.

That said, however, because we only need a single function in a single library, and we know at runtime the conditions when we'd want to load said library (the process was launched by `systemd`), we could link at runtime with `dlsym` so we can ship one binary that Does the Right Thing wherever it is run.

On-demand socket-based activation is critical for performance on whichever platforms support it, and we should leverage it on systems where it is available

**Comment by conradev** [comment]
It looks like dynamically loading libsystemd is how a lot of other software is packaged, i.e. `go-systemd`: https://github.com/coreos/go-systemd/blob/d5623bf85e8e73ae6352f78ee6b55a287619dd4e/util/util_cgo.go#L106-L121

**Comment by conradev** [comment]
A few things:

- We should pick a well-known location for a Unix socket (i.e. `burrow.sock`)

- We should support a CLI subcommand to run in daemon mode
    - If libsystemd is present and we are launched by it, dynamically load libsystemd, get the file descriptor from systemd
    - Else, open a listener on the Unix socket

- For now, let's use HTTP and JSON
    - On the server, let's use `axum`
    - On the client, let's use `reqwest`? or `hyper`
    - Requests should be serialized with `serde`

**Comment by davnotdev** [comment]
Should cli users be able to start tun with options? If so, can we add `serde` to `tun`'s dependencies so that `TunOptions` can be serialized?

**Comment by davnotdev** [comment]
@conradev, I feel like it would be much easier to go without HTTP. Right now, unix domain socket support for rust's HTTP libraries are *meh* at best. Using `tokio`'s `UnixStream` with `serde_json`, and reading line by line would work much better. It's much simpler, and `serde_json` serializes data onto a single line anyway. Does this sound fine?

**Comment by conradev** [comment]
Yep, that sounds great! I realized that it might be an issue after suggesting it

I’d suggest using a body type with a request ID so that our system works with out of order responses (perhaps JSON-RPC)

**Comment by conradev** [comment]
Ethereum uses newline-delimited JSON-RPC for its Unix socket, and it seems like a common pattern

Browsers use length-delimited JSON for native hosts

**Comment by reesericci** [comment]
can we just use D-Bus for the daemon?

**Comment by davnotdev** [comment]
Yeah, dbus would also work, but it's built on unix sockets which aren't much of a hassle to work with anyway. As for the `libsystemd` stuff, I believe that's just slightly more efficient?

**Comment by conradev** [comment]
I'd prefer a unix socket over d-bus because it is more portable – we can use the same mechanism on iOS/macOS

The libsystemd stuff is an optimization to be more efficient and it works with any socket type

**Comment by reesericci** [comment]
Isn't d-bus the linux desktop standard though?
