### ISSUE TITLE
Build command-line interface

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#7]
We should use [`clap`](https://docs.rs/clap/latest/clap/) and it's `derive` functionality

**Comment by sampoder** [comment]
Cool if I take a stab at working on this? Would we want to create another sub-directory that's like `cli` or a cooler name

**Comment by conradev** [comment]
@sampoder I originally had someone else working on this, but they haven't had time to work on it yet

**Comment by sampoder** [comment]
I'm down to! I plan to get working on it tomorrow.
