### ISSUE TITLE
Write a Dockerfile for the burrow server component

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#73]

**Comment by anddddrew** [comment]
i can do this

**Comment by 0xacn** [comment]
is this in the `/tun` folder?

**Comment by Muirrum** [comment]
This would probably end up in the root directory, but we don't have a server component to write a dockerfile for yet. That's blocked by #72 at least, as well as #93

**Comment by conradev** [comment]
@0xacn Building a Docker container that just builds the burrow CLI would be a great first step.

My ideal would be a `FROM scratch` container containing the `musl` static build, for both x86_64 and aarch64 Linux, with a Github Actions flow to upload the image to Github Packages
