### ISSUE TITLE
Configure interface appropriately on all platforms

### ISSUE THREAD

**Issue by Muirrum** [hackclub/burrow#87]
Bring up the interface, set name, set IP range to something "reasonable"

**Comment by conradev** [comment]
Let's use the shared address space and a random IP within share address space for now

The main thing we want to do is:
- Configure the name from the burrow crate
- Start the interface

**Comment by karamassie** [comment]
@Muirrum is this all ready to be passed on to someone else (since youre so busy)?

**Comment by Muirrum** [comment]
yup

**Comment by karamassie** [comment]
@Muirrum -- same with this, can we pass this along to someone else?

**Comment by Muirrum** [comment]
yup, all my tasks are good to be reassigned
