### ISSUE TITLE
Add ability to ask for root permissions

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#9]

**Comment by davnotdev** [comment]
Would using `sudo` or `pkexec` not suffice? On Linux specifically, I feel like asking for permissions with something like polkit would be complete overkill.

**Comment by conradev** [comment]
Yes, those are good points! There is a reason things are they way they are

I should have phrased this as "I want a solution to a specific problem that I have", which is that I want a good way to spawn and attach to the process from CodeLLDB. On macOS, the process needs uid 0, and on Linux, CAP_NET_ADMIN.

For now spawning and attaching can just be separate, but I've been thinking about other solutions

(Perhaps a dev server mode of sorts that runs privileged and can create the tunnel for anything that asks? Only if it's easy)

**Comment by conradev** [comment]
This was solved for now by making the runner `sudo` on Linux platforms
