### ISSUE TITLE
Add a note to Getting Started to select the current version in Xcode

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#98]

**Comment by sporeball** [comment]
how should this read - add "Make sure to install the **latest version**."?

**Comment by conradev** [comment]
@sporeball it is actually about _selecting_ the correct version of Xcode. macOS has a notion of the "current" Xcode or the default toolchain. The `xcode-select` tool on macOS controls this:

```
$ xcode-select -p
/Application/Xcode/Xcode.app/Contents/Developer
$ sudo xcode-select --switch /Application/Xcode/Xcode-beta.app
$ xcode-select -p
/Application/Xcode/Xcode-beta.app/Contents/Developer
```
